version: '3'

services:
  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_PASSWORD=minesweeper
      - POSTGRES_USER=minesweeper
      - POSTGRES_DB=minesweeper
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data