GIT_DATE := $(firstword $(shell git --no-pager show --date=short --format="%ai" --name-only))
GIT_VERSION := $(shell git rev-parse HEAD)
BIN_VERSION := $(GIT_VERSION)|$(GIT_DATE)
MKFILE_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
CUR_DIR := $(patsubst %/,%,$(dir $(MKFILE_PATH)))

.PHONY: server

# re-builds the sql boiler models
sql-boiler: clean-sql-boiler
	cd ~/go/bin;\
	~/go/bin/sqlboiler --struct-tag-casing camel --no-tests -c $(CUR_DIR)/database.toml -o $(CUR_DIR)/models psql

# removes the autogenerated sql boiler files
clean-sql-boiler:
	rm -rf models/*

# remove unused dependencies and tidy up modules
mod-tydy:
	go mod tidy

# lints the project
lint:
	~/go/bin/golangci-lint run

server: lint
	go build -tags=jsoniter -ldflags "-X http.response.minesweeperVersion=$(BIN_VERSION)" cmd/server/server.go

# outputs the current version
version:
	@echo "$(BIN_VERSION)"

test:
	go test ./...
