// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GameBoardPoints string
	GameOperations  string
	Games           string
	Players         string
}{
	GameBoardPoints: "game_board_points",
	GameOperations:  "game_operations",
	Games:           "games",
	Players:         "players",
}
